### ISSUE TITLE
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3268824608) is greater than 2 GiB

### ISSUE THREAD

**Issue by ray040237** [hyparam/hyllama#3]
Debugger attached.
Waiting for the debugger to disconnect...
node:fs:415
      throw new ERR_FS_FILE_TOO_LARGE(size);
            ^

RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3268824608) is greater than 2 GiB
    at tryCreateBuffer (node:fs:415:13)
    at Module.readFileSync (node:fs:468:14)
    at main (D:\js\readcpp\test.js:5:23) {
  code: 'ERR_FS_FILE_TOO_LARGE'
}

**Comment by platypii** [comment]
Thanks @ray040237 for filing this issue. Node does not like to do `readFileSync` on files larger than 2gb.

I have updated the README with a new example which instead uses `fs.readSync` to read only the first 1mb of the file into memory, which will typically be large enough to contain the metadata and tensor info.

```js
const { ggufMetadata } = await import('hyllama')
const fs = await import('fs')

// Read first 1mb of gguf file
const fd = fs.openSync('example.gguf', 'r')
const buffer = new Uint8Array(1000000)
fs.readSync(fd, buffer, 0, 1000000, 0)
fs.closeSync(fd)

// Parse metadata and tensor info
const { metadata, tensorInfos } = ggufMetadata(buffer.buffer)
```

Please let me know if that helps fix your issue! Thanks!
